# Generated by Django 4.2 on 2025-05-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='materias.career'),
        ),
    ]
