# Generated by Django 4.2 on 2025-07-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='usuarios_us_last_na_ba54a2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='usuarios_us_first_n_cc1145_idx'),
        ),
    ]
