# Generated by Django 4.2 on 2025-05-14 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_remove_materia_anio_remove_materia_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripciones', '0002_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='fecha_registro',
            new_name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='valor',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='InscripcionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.career')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a Carrera',
                'verbose_name_plural': 'Inscripciones a Carreras',
                'unique_together': {('estudiante', 'carrera')},
            },
        ),
    ]
