# Generated by Django 4.2 on 2025-07-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_rename_fecha_registro_nota_fecha_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion'),
        ),
    ]
